/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import modelo.IModeloSalaDeEspera;
import tipoEventos.EventoSalaEspera;
import contratos.controladoresMVC.iControlSalaEspera;
import javax.swing.JOptionPane;

/**
 *
 * @author benja
 */
public class VistaSalaEspera extends javax.swing.JFrame implements ObservadorSalaDeEspera {

    private iControlSalaEspera control;

    /**
     * Creates new form VistaSalaEspera
     */
    public VistaSalaEspera(iControlSalaEspera control) {
        this.control = control;
        this.setTitle("RummyKub | Vive la experiencia!");
        this.setSize(920, 550);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarPartida = new javax.swing.JButton();
        avatarJugador2 = new javax.swing.JLabel();
        avatarJugador3 = new javax.swing.JLabel();
        avatarJugador4 = new javax.swing.JLabel();
        avatarJugador1 = new javax.swing.JLabel();
        fondoNombre4 = new javax.swing.JPanel();
        nombreJugador4 = new javax.swing.JLabel();
        fondoNombre3 = new javax.swing.JPanel();
        nombreJugador3 = new javax.swing.JLabel();
        fondoNombre2 = new javax.swing.JPanel();
        nombreJugador2 = new javax.swing.JLabel();
        fondoNombre1 = new javax.swing.JPanel();
        nombreJugador1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        btnIniciarPartida.setBackground(new java.awt.Color(246, 220, 105));
        btnIniciarPartida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIniciarPartida.setForeground(new java.awt.Color(153, 102, 0));
        btnIniciarPartida.setText("Iniciar Partida");
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarPartida);
        btnIniciarPartida.setBounds(320, 380, 290, 70);

        avatarJugador2.setForeground(new java.awt.Color(13, 87, 26));
        avatarJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarJugador2.setText("...");
        getContentPane().add(avatarJugador2);
        avatarJugador2.setBounds(180, 180, 40, 40);

        avatarJugador3.setForeground(new java.awt.Color(13, 87, 26));
        avatarJugador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarJugador3.setText("...");
        getContentPane().add(avatarJugador3);
        avatarJugador3.setBounds(180, 240, 40, 40);

        avatarJugador4.setForeground(new java.awt.Color(13, 87, 26));
        avatarJugador4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarJugador4.setText("...");
        getContentPane().add(avatarJugador4);
        avatarJugador4.setBounds(180, 310, 40, 40);

        avatarJugador1.setForeground(new java.awt.Color(16, 101, 30));
        avatarJugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarJugador1.setText("...");
        getContentPane().add(avatarJugador1);
        avatarJugador1.setBounds(180, 120, 40, 40);

        fondoNombre4.setBackground(new java.awt.Color(237, 218, 218));

        nombreJugador4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreJugador4.setForeground(new java.awt.Color(0, 0, 0));
        nombreJugador4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador4.setText("Esperando jugador 4...");
        fondoNombre4.add(nombreJugador4);

        getContentPane().add(fondoNombre4);
        fondoNombre4.setBounds(260, 310, 400, 40);

        fondoNombre3.setBackground(new java.awt.Color(237, 218, 218));

        nombreJugador3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreJugador3.setForeground(new java.awt.Color(0, 0, 0));
        nombreJugador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador3.setText("Esperando jugador 3...");
        fondoNombre3.add(nombreJugador3);

        getContentPane().add(fondoNombre3);
        fondoNombre3.setBounds(260, 240, 400, 40);

        fondoNombre2.setBackground(new java.awt.Color(237, 218, 218));

        nombreJugador2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreJugador2.setForeground(new java.awt.Color(0, 0, 0));
        nombreJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador2.setText("Esperando jugador 2...");
        fondoNombre2.add(nombreJugador2);

        getContentPane().add(fondoNombre2);
        fondoNombre2.setBounds(260, 180, 400, 40);

        fondoNombre1.setBackground(new java.awt.Color(237, 218, 218));

        nombreJugador1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreJugador1.setForeground(new java.awt.Color(0, 0, 0));
        nombreJugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador1.setText("Jugador1");
        fondoNombre1.add(nombreJugador1);

        getContentPane().add(fondoNombre1);
        fondoNombre1.setBounds(260, 120, 400, 40);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 235, 126));
        txtTitulo.setText("Sala de espera");
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(270, 30, 400, 90);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoRummy.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo);
        fondo.setBounds(-10, -10, 930, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        if (control != null) {
            ((control.ControlSalaDeEspera) control).enviarVoto();
        }
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    /**
     * Recibe la cadena "sucia" del servidor y actualiza la UI.
     *
     * @param data Ejemplo: "ID1,Nombre$Avatar$C1..;ID2,Nombre2$Avatar..."
     */
    public void actualizarJugadores(String data) {
        System.out.println("[VistaSalaEspera] Datos recibidos: " + data);
        resetearVista();

        if (data == null || data.isEmpty()) {
            return;
        }

        String[] jugadores = data.split(";");

        // 1. PINTAR JUGADORES (Ahora soportamos hasta 4)
        if (jugadores.length > 0) {
            pintarJugador(jugadores[0], nombreJugador1, avatarJugador1);
        }
        if (jugadores.length > 1) {
            pintarJugador(jugadores[1], nombreJugador2, avatarJugador2);
        }
        if (jugadores.length > 2) {
            pintarJugador(jugadores[2], nombreJugador3, avatarJugador3);
        }
        if (jugadores.length > 3) {
            pintarJugador(jugadores[3], nombreJugador4, avatarJugador4);
        }

        // 2. LOGICA DEL BOTÓN DE INICIO
        // Solo habilitamos el botón si hay 2 o más jugadores conectados
        if (jugadores.length >= 2) {
            btnIniciarPartida.setEnabled(true);
            btnIniciarPartida.setText("¡Estoy Listo!");
        } else {
            btnIniciarPartida.setEnabled(false);
            btnIniciarPartida.setText("Esperando jugadores...");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarJugador1;
    private javax.swing.JLabel avatarJugador2;
    private javax.swing.JLabel avatarJugador3;
    private javax.swing.JLabel avatarJugador4;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondoNombre1;
    private javax.swing.JPanel fondoNombre2;
    private javax.swing.JPanel fondoNombre3;
    private javax.swing.JPanel fondoNombre4;
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void pintarJugador(String rawData, JLabel lblNombre, JLabel lblAvatar) {
        try {
            // rawData: "ID,Nombre$Avatar$Color..."
            String[] primeraSeparacion = rawData.split(",");
            if (primeraSeparacion.length > 1) {
                String payload = primeraSeparacion[1];
                String[] datosUsuario = payload.split("\\$");

                String nombre = datosUsuario[0];
                String idAvatar = (datosUsuario.length > 1) ? datosUsuario[1] : "1";

                lblNombre.setText(nombre);

                // Si el ID es solo un número "1", le pegamos "avatar" -> "avatar1.png"
                String nombreArchivo = "avatar" + idAvatar + ".png";
                colocarImagen(lblAvatar, "/avatares/" + nombreArchivo);
            }
        } catch (Exception e) {
            System.err.println("Error pintando jugador: " + e.getMessage());
        }
    }

    private void colocarImagen(JLabel label, String ruta) {
        try {
            java.net.URL imgURL = getClass().getResource(ruta);
            if (imgURL != null) {
                ImageIcon icon = new ImageIcon(imgURL);
                Image img = icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
                label.setIcon(new ImageIcon(img));
            }
        } catch (Exception e) {
        }
    }

    private void resetearVista() {
        // Jugador 1
        if (nombreJugador1 != null) nombreJugador1.setText("Esperando...");
        if (avatarJugador1 != null) avatarJugador1.setIcon(null);

        // Jugador 2
        if (nombreJugador2 != null) nombreJugador2.setText("Esperando...");
        if (avatarJugador2 != null) avatarJugador2.setIcon(null);

        // Jugador 3
        if (nombreJugador3 != null) nombreJugador3.setText("Esperando...");
        if (avatarJugador3 != null) avatarJugador3.setIcon(null);

        // Jugador 4
        if (nombreJugador4 != null) nombreJugador4.setText("Esperando...");
        if (avatarJugador4 != null) avatarJugador4.setIcon(null);
    }

    @Override
    public void actualiza(IModeloSalaDeEspera modelo, EventoSalaEspera evento, Object datos) {
        switch (evento) {
            case MOSTRAR_SALA:
                this.setVisible(true);
                break;

            case CERRAR_CU:
                this.setVisible(false);
                this.dispose();
                break;

            case VOTO_REGISTRADO:
                btnIniciarPartida.setEnabled(false);
                btnIniciarPartida.setText("Esperando al otro...");
                break;

            case ACTUALIZAR_DATOS_JUGADORES:
                if (datos instanceof String) {
                    actualizarJugadores((String) datos);
                }
                break;
            case PETICION_VOTO:
                String idCandidato = (String) datos;
                int respuesta = JOptionPane.showConfirmDialog(
                        this,
                        "El jugador '" + idCandidato + "' solicita unirse.\n¿Permitir acceso?",
                        "Votación",
                        JOptionPane.YES_NO_OPTION
                );
                boolean votoPositivo = (respuesta == JOptionPane.YES_OPTION);
                control.enviarVoto(votoPositivo);
                break;

            default:
                break;
        }
    }
}
