/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.ControlSalaEspera;
import javax.swing.JOptionPane;
import modelo.IModeloSalaEspera;

/**
 *
 * @author benja
 */
public class VistaSalaEspera extends javax.swing.JFrame implements ObservadorSalaEspera {

    private ControlSalaEspera controlador;

    /**
     * Creates new form VistaSalaEspera
     */
    public VistaSalaEspera(ControlSalaEspera control) {
        this.controlador = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSolicitarInicioPartida = new javax.swing.JButton();
        lblJugador1 = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblJugador4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        btnSolicitarInicioPartida.setBackground(new java.awt.Color(80, 118, 78));
        btnSolicitarInicioPartida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSolicitarInicioPartida.setText("Iniciar Partida");
        btnSolicitarInicioPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarInicioPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitarInicioPartida);
        btnSolicitarInicioPartida.setBounds(350, 340, 220, 70);

        lblJugador1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblJugador1.setText("Esperando jugador...");
        getContentPane().add(lblJugador1);
        lblJugador1.setBounds(270, 120, 380, 32);

        lblJugador3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblJugador3.setText("Esperando jugador...");
        getContentPane().add(lblJugador3);
        lblJugador3.setBounds(270, 220, 380, 30);

        lblJugador2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblJugador2.setText("Esperando jugador...");
        getContentPane().add(lblJugador2);
        lblJugador2.setBounds(270, 170, 380, 30);

        lblJugador4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblJugador4.setText("Esperando jugador...");
        getContentPane().add(lblJugador4);
        lblJugador4.setBounds(270, 270, 370, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 235, 126));
        jLabel2.setText("Sala de espera");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 30, 400, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoRummy.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 920, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarInicioPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarInicioPartidaActionPerformed
        controlador.solicitarInicioPartida();
    }//GEN-LAST:event_btnSolicitarInicioPartidaActionPerformed

    @Override
    public void actualiza(IModeloSalaEspera modelo, String evento, Object datos) {
        String eventoStr = (String) evento;

        switch (eventoStr) {
            case "MOSTRAR_PANTALLA":
                this.setVisible(true);
                break;

            case "PETICION_VOTO":
                String idCandidato = (String) datos;
                int respuesta = JOptionPane.showConfirmDialog(
                        this,
                        "El jugador '" + idCandidato + "' solicita unirse.\n¿Permitir acceso?",
                        "Votación",
                        JOptionPane.YES_NO_OPTION
                );
                boolean votoPositivo = (respuesta == JOptionPane.YES_OPTION);
                controlador.enviarVoto(votoPositivo);
                break;

            case "ACTUALIZAR_LISTA":
                if (datos instanceof String[]) {
                    actualizarLabels((String[]) datos);
                }
                break;
            case "JUEGO_INICIADO":
                // 1. Ocultar esta pantalla
                this.setVisible(false);
                // 2. Navegar a la siguiente
                controlador.navegacionEjercerTurno();
                break;
            case "ERROR_INICIO":
                JOptionPane.showMessageDialog(this,
                        "No se pudo iniciar la partida.\n"
                        + "Verifica que haya al menos 2 jugadores y máximo 4.",
                        "Error al Iniciar", JOptionPane.WARNING_MESSAGE);
                break;
            case "CERRAR_SALA":
                this.dispose();
                break;
        }
    }

    private void actualizarLabels(String[] jugadores) {
        // 1. Limpiar todos primero
        lblJugador1.setText("Esperando...");
        lblJugador2.setText("Esperando...");
        lblJugador3.setText("Esperando...");
        lblJugador4.setText("Esperando...");
        if (jugadores.length > 0) {
            lblJugador1.setText(jugadores[0]);
        }
        if (jugadores.length > 1) {
            lblJugador2.setText(jugadores[1]);
        }
        if (jugadores.length > 2) {
            lblJugador3.setText(jugadores[2]);
        }
        if (jugadores.length > 3) {
            lblJugador4.setText(jugadores[3]);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolicitarInicioPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblJugador4;
    // End of variables declaration//GEN-END:variables

}
