/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import eventos.Evento;
import contratos.controladoresMVC.iControlCUPrincipal;
import javax.swing.JOptionPane;
import Modelo.IModeloLobby;

/**
 *
 * @author benja
 */
public class VistaLobby extends javax.swing.JFrame implements ObservadorLobby {

    /**
     * Creates new form VistaLobby
     */
    iControlCUPrincipal control;

    public VistaLobby(iControlCUPrincipal control) {
        this.control = control;
        this.setTitle("RummyKub | Vive la experiencia!");
        this.setSize(920, 550);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 220, 105));
        jLabel2.setText("Rummy");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 30, 220, 60);

        jButton1.setBackground(new java.awt.Color(255, 235, 126));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Crear partida");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 130, 280, 120);

        jButton2.setBackground(new java.awt.Color(255, 235, 126));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Unirse a partida");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 280, 280, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoRummy.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-4, -4, 910, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        control.iniciarCreacionPartida();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        control.SolicitarUnirseAPartida();
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualiza(IModeloLobby modelo, Evento evento) {
        switch (evento) {
            case ACCESO_DENEGADO:
                JOptionPane.showMessageDialog(this, "No se pudo unir: La partida esta llena (4 jugadores) o falta partida a la cual unirse", "No se pudo unir", JOptionPane.WARNING_MESSAGE);
                break;

            case CERRAR_CU:
                this.setVisible(false);
                this.dispose();
                break;

            case INICIO:
                this.setVisible(true);
                break;

            case CREAR_PARTIDA:
                
                // MOCK, REDIRECCION A REGISTRO
                System.out.println("[VistaLobby] Partida creada/solicitada. Redirigiendo a Registro de Jugador...");
                this.setVisible(false);

                // MOCK: Vamos directo al registro
                control.casoUsoConfigurarPartida();
                break;

            case SOLICITAR_INICIO:
                break;

            case SOLICITAR_UNIRSE_A_PARTIDA:
                if (modelo.getPartida() == null) {
                    System.out.println("No hay partida a la que unirse");
                } else {
                    System.out.println("Se solicito unirse a partida");
                }
                break;

            case PARTIDA_EXISTENTE:
                JOptionPane.showMessageDialog(this, "No se puede crear una Nueva Partida, ya existe una corriendo localmente. Uniendose Automaticamente..");
                break;

            case ACTUALIZAR_SALA:
                if (control instanceof Control.ControlCUPrincipal) {
                    ((Control.ControlCUPrincipal) control).procesarActualizacionSala();
                }
                break;

            case INICIO_JUEGO:
                System.out.println("[VistaLobby] El juego ha iniciado. Cerrando lobby.");
                this.setVisible(false);
                this.dispose();
                break;

            default:
                throw new AssertionError();
        }
    }
}
