package Vista;

import Modelo.IModeloLobby;
import eventos.Evento;
import contratos.controladoresMVC.iControlCUPrincipal;
import javax.swing.JOptionPane;

/**
 * Esta clase representa la vista principal de todo el sistema.
 *
 * @author Sebastian Moreno
 */
public class VistaLobby extends javax.swing.JFrame implements ObservadorLobby {

    iControlCUPrincipal control;

    public VistaLobby(iControlCUPrincipal control) {
        this.control = control;
        this.setTitle("RummyKub | Vive la experiencia!");
        this.setSize(920, 550);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnCrearPartida = new javax.swing.JButton();
        btnUnirsePartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        title.setForeground(new java.awt.Color(246, 220, 105));
        title.setText("Rummy");
        getContentPane().add(title);
        title.setBounds(340, 30, 220, 60);

        btnCrearPartida.setBackground(new java.awt.Color(255, 235, 126));
        btnCrearPartida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCrearPartida.setText("Crear partida");
        btnCrearPartida.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCrearPartida.setMinimumSize(new java.awt.Dimension(100, 30));
        btnCrearPartida.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCrearPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPartidaMouseClicked(evt);
            }
        });
        getContentPane().add(btnCrearPartida);
        btnCrearPartida.setBounds(320, 130, 280, 120);

        btnUnirsePartida.setBackground(new java.awt.Color(255, 235, 126));
        btnUnirsePartida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUnirsePartida.setText("Unirse a partida");
        btnUnirsePartida.setMaximumSize(new java.awt.Dimension(100, 30));
        btnUnirsePartida.setMinimumSize(new java.awt.Dimension(100, 30));
        btnUnirsePartida.setPreferredSize(new java.awt.Dimension(100, 30));
        btnUnirsePartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnirsePartidaMouseClicked(evt);
            }
        });
        getContentPane().add(btnUnirsePartida);
        btnUnirsePartida.setBounds(320, 280, 280, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoRummy.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-4, -4, 910, 530);
    }// </editor-fold>                        

    private void btnCrearPartidaMouseClicked(java.awt.event.MouseEvent evt) {                                             
        control.iniciarCreacionPartida();
    }                                            

    private void btnUnirsePartidaMouseClicked(java.awt.event.MouseEvent evt) {                                              
        control.SolicitarUnirseAPartida();
    }                                             

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnUnirsePartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel title;
    // End of variables declaration                   

    @Override
    public void actualiza(IModeloLobby modelo, Evento evento) {
        switch (evento) {
            case ACCESO_DENEGADO:
                JOptionPane.showMessageDialog(this, "No se pudo unir: La partida esta llena (4 jugadores) o falta partida a la cual unirse", "No se pudo unir", JOptionPane.WARNING_MESSAGE);
                break;
            case CERRAR_CU:
                this.setVisible(false);
                break;

            case INICIO:
                this.setVisible(true);
                break;

            case CREAR_PARTIDA:
                // MOCK, REDIRECCION A REGISTRO
                System.out.println("[VistaLobby] Partida creada/solicitada. Redirigiendo a Registro de Jugador...");
                this.setVisible(false);
                // MOCK: Vamos directo al registro
                control.casoUsoConfigurarPartida();
                break;
            case SOLICITAR_UNIRSE_A_PARTIDA:
                if (modelo.getPartida() == null) {
                    System.out.println("No hay partida a la que unirse");
                } else {
                    System.out.println("Se solicito unirse a partida");
                }
                break;

            case PARTIDA_EXISTENTE:
                JOptionPane.showMessageDialog(this, "No se puede crear una Nueva Partida, ya existe una corriendo localmente. Uniendose Automaticamente..");
                break;

            case ACTUALIZAR_SALA:
                control.entrarSalaEspera();
                break;

            case INICIO_JUEGO:
                System.out.println("[VistaLobby] El juego ha iniciado. Cerrando lobby.");
                this.setVisible(false);
                this.dispose();
                break;

            default:
                throw new AssertionError();
        }
    }
}