/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Control.Control;
import eventos.Evento;
import javax.swing.JOptionPane;
import Modelo.iModelo;

/**
 *
 * @author benja
 */
public class VistaLobby extends javax.swing.JFrame implements Observador {

    /**
     * Creates new form VistaLobby
     */
    Control control;

    public VistaLobby(Control control) {
        this.control = control;
        this.setTitle("RummyKub | Vive la experiencia!");
        this.setSize(920, 550);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCrearPartida = new javax.swing.JButton();
        btnUnirseAPartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 220, 105));
        jLabel2.setText("Rummy");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 30, 220, 60);

        btnCrearPartida.setBackground(new java.awt.Color(255, 235, 126));
        btnCrearPartida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCrearPartida.setText("Crear partida");
        btnCrearPartida.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCrearPartida.setMinimumSize(new java.awt.Dimension(100, 30));
        btnCrearPartida.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCrearPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPartidaMouseClicked(evt);
            }
        });
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearPartida);
        btnCrearPartida.setBounds(320, 130, 280, 120);

        btnUnirseAPartida.setBackground(new java.awt.Color(255, 235, 126));
        btnUnirseAPartida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUnirseAPartida.setText("Unirse a partida");
        btnUnirseAPartida.setMaximumSize(new java.awt.Dimension(100, 30));
        btnUnirseAPartida.setMinimumSize(new java.awt.Dimension(100, 30));
        btnUnirseAPartida.setPreferredSize(new java.awt.Dimension(100, 30));
        btnUnirseAPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseAPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnirseAPartida);
        btnUnirseAPartida.setBounds(320, 280, 280, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoRummy.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 900, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void btnUnirseAPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseAPartidaActionPerformed
        control.SolicitarUnirseAPartida();
    }//GEN-LAST:event_btnUnirseAPartidaActionPerformed

    private void btnCrearPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPartidaMouseClicked
        control.iniciarCreacionPartida();
    }//GEN-LAST:event_btnCrearPartidaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnUnirseAPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualiza(iModelo modelo, Evento evento) {
        switch (evento) {
            case CREAR_PARTIDA:
                this.setVisible(false);
                control.casoUsoConfigurarPartida();
                break;

            case ERROR_NO_HAY_PARTIDA:
                JOptionPane.showMessageDialog(this,
                        "No hay ninguna partida a la que unirse, puedes configurar y crear una si asi lo deseas.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
                break;

            case ERROR_PARTIDA_INICIADA:
                JOptionPane.showMessageDialog(this,
                        "La partida ya está iniciada. No puedes unirte.",
                        "Error", JOptionPane.WARNING_MESSAGE);
                break;

            case UNION_RECHAZADA:
                JOptionPane.showMessageDialog(this,
                        "Tu solicitud de unirse a partida fue rechazada.",
                        "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
                break;

            case UNION_ACEPTADA:
                JOptionPane.showMessageDialog(this, "¡Solicitud aceptada! Entrando a sala de espera...", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                break;
        }
    }
}
