/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import DTO.FichaJuegoDTO;
import DTO.GrupoDTO;
import DTO.JuegoDTO;
import Modelo.IModelo;
import Vista.Objetos.FichaUI;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author benja
 */
public class VistaTablero extends javax.swing.JFrame implements Observador {

    private Controlador control;
    private boolean fichasInicializadas = false;

    /**
     * Creates new form VistaTableross
     */
    public VistaTablero(Controlador control) {
        this.control = control;
        this.setSize(920, 550);
        this.setName("Rummy");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUIjuego = new javax.swing.JPanel();
        panelJugador4 = new Vista.PanelRound();
        panelJugador1 = new Vista.PanelRound();
        panelMano = new Vista.PanelRound();
        panelJugador3 = new Vista.PanelRound();
        mazo = new Vista.PanelRound();
        panelJugador2 = new Vista.PanelRound();
        panelTablero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GUIjuego.setBackground(new java.awt.Color(0, 0, 0));
        GUIjuego.setLayout(null);

        panelJugador4.setRoundBottomLeft(40);
        panelJugador4.setRoundBottomRight(40);
        panelJugador4.setRoundTopLeft(40);
        panelJugador4.setRoundTopRight(40);

        javax.swing.GroupLayout panelJugador4Layout = new javax.swing.GroupLayout(panelJugador4);
        panelJugador4.setLayout(panelJugador4Layout);
        panelJugador4Layout.setHorizontalGroup(
            panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelJugador4Layout.setVerticalGroup(
            panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        GUIjuego.add(panelJugador4);
        panelJugador4.setBounds(0, 0, 120, 110);

        panelJugador1.setRoundBottomLeft(40);
        panelJugador1.setRoundBottomRight(40);
        panelJugador1.setRoundTopLeft(40);
        panelJugador1.setRoundTopRight(40);

        javax.swing.GroupLayout panelJugador1Layout = new javax.swing.GroupLayout(panelJugador1);
        panelJugador1.setLayout(panelJugador1Layout);
        panelJugador1Layout.setHorizontalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelJugador1Layout.setVerticalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        GUIjuego.add(panelJugador1);
        panelJugador1.setBounds(0, 390, 120, 110);

        panelMano.setRoundBottomLeft(40);
        panelMano.setRoundBottomRight(40);
        panelMano.setRoundTopLeft(40);
        panelMano.setRoundTopRight(40);
        panelMano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManoMouseClicked(evt);
            }
        });
        panelMano.setLayout(null);
        GUIjuego.add(panelMano);
        panelMano.setBounds(160, 380, 580, 120);

        panelJugador3.setRoundBottomLeft(40);
        panelJugador3.setRoundBottomRight(40);
        panelJugador3.setRoundTopLeft(40);
        panelJugador3.setRoundTopRight(40);

        javax.swing.GroupLayout panelJugador3Layout = new javax.swing.GroupLayout(panelJugador3);
        panelJugador3.setLayout(panelJugador3Layout);
        panelJugador3Layout.setHorizontalGroup(
            panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelJugador3Layout.setVerticalGroup(
            panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        GUIjuego.add(panelJugador3);
        panelJugador3.setBounds(780, 0, 120, 110);

        mazo.setRoundBottomLeft(40);
        mazo.setRoundBottomRight(40);
        mazo.setRoundTopLeft(40);
        mazo.setRoundTopRight(40);

        javax.swing.GroupLayout mazoLayout = new javax.swing.GroupLayout(mazo);
        mazo.setLayout(mazoLayout);
        mazoLayout.setHorizontalGroup(
            mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        mazoLayout.setVerticalGroup(
            mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        GUIjuego.add(mazo);
        mazo.setBounds(790, 250, 60, 80);

        panelJugador2.setRoundBottomLeft(40);
        panelJugador2.setRoundBottomRight(40);
        panelJugador2.setRoundTopLeft(40);
        panelJugador2.setRoundTopRight(40);

        javax.swing.GroupLayout panelJugador2Layout = new javax.swing.GroupLayout(panelJugador2);
        panelJugador2.setLayout(panelJugador2Layout);
        panelJugador2Layout.setHorizontalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelJugador2Layout.setVerticalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        GUIjuego.add(panelJugador2);
        panelJugador2.setBounds(780, 390, 120, 110);

        panelTablero.setBackground(new java.awt.Color(153, 153, 153));
        panelTablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelTableroMouseReleased(evt);
            }
        });
        panelTablero.setLayout(null);
        GUIjuego.add(panelTablero);
        panelTablero.setBounds(130, 40, 640, 320);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoRummy.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        GUIjuego.add(jLabel1);
        jLabel1.setBounds(0, 0, 1322, 902);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(GUIjuego, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(GUIjuego, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelManoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelManoMouseClicked

    private void panelTableroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTableroMouseReleased
   
    }//GEN-LAST:event_panelTableroMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GUIjuego;
    private javax.swing.JLabel jLabel1;
    private Vista.PanelRound mazo;
    private Vista.PanelRound panelJugador1;
    private Vista.PanelRound panelJugador2;
    private Vista.PanelRound panelJugador3;
    private Vista.PanelRound panelJugador4;
    private Vista.PanelRound panelMano;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualiza(IModelo modelo) {
        if (!fichasInicializadas) {
            incializarFichasManoPrueba(modelo);
            fichasInicializadas = true; // marca que ya se ejecutó
        } else {
            pintarFichasTablero(modelo, control);
        }

    }

    public void pintarFichasTablero(IModelo modelo, Controlador controlador) {
        // 1️⃣ Obtener el JuegoDTO desde el modelo
        JuegoDTO juego = modelo.getTablero();
        List<GrupoDTO> grupos = juego.getGruposEnTablero();

        // 2️⃣ Limpiar el panel del tablero antes de pintar
        panelTablero.removeAll();
        panelTablero.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));

        // 3️⃣ Recorrer cada grupo
        for (GrupoDTO grupoDTO : grupos) {
            // Crear un panel para el grupo
            JPanel panelGrupo = new JPanel();
            panelGrupo.setBorder(BorderFactory.createTitledBorder(grupoDTO.getTipo()));
            panelGrupo.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));

            // Recorrer las fichas del grupo
            for (FichaJuegoDTO fichaDTO : grupoDTO.getFichasGrupo()) {
                // Crear un FichaUI en lugar de JButton
                FichaUI fichaUI = new FichaUI(
                        fichaDTO.getNumeroFicha(),
                        fichaDTO.getColor(),
                        fichaDTO.isComodin(),
                        controlador
                );

                fichaUI.setPreferredSize(new Dimension(40, 60));
                panelGrupo.add(fichaUI);

                // 🔹 Eliminar la ficha de la mano si existe allí
                modelo.getMano().removeIf(f
                        -> f.getNumeroFicha() == fichaDTO.getNumeroFicha()
                        && f.getColor().equals(fichaDTO.getColor())
                        && f.isComodin() == fichaDTO.isComodin()
                );
            }

            // Agregar el panel del grupo al tablero
            panelTablero.add(panelGrupo);
        }

        // 4️⃣ Refrescar la vista
        panelTablero.revalidate();
        panelTablero.repaint();
    }

    public void incializarFichasManoPrueba(IModelo modelo) {

        List<FichaJuegoDTO> fichasMano = modelo.getMano();
        int startX = panelMano.getX() + 10; // posición inicial relativa al panelMano
        int startY = panelMano.getY() + 10;

        int xPos = startX;
        int yPos = startY;

        for (FichaJuegoDTO fichaJuegoDTO : fichasMano) {
            int numero = fichaJuegoDTO.getNumeroFicha();
            Color color = fichaJuegoDTO.getColor();
            boolean comodin = fichaJuegoDTO.isComodin();

            FichaUI fichaUI = new FichaUI(numero, color, comodin, control);
            fichaUI.setSize(35, 50); // tamaño fijo
            fichaUI.setLocation(xPos, yPos);

            fichaUI.setOpaque(false); // transparente, para que no tape fondo
            GUIjuego.add(fichaUI); // agregamos directamente al panel principal
            GUIjuego.setComponentZOrder(fichaUI, 0); // trae la ficha al frente

            xPos += 40; // separación entre fichas
        }
        yPos += 80;
        xPos = startX;

        revalidate();
        repaint();
    }

}
