/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import DTO.FichaJuegoDTO;
import DTO.GrupoDTO;
import DTO.JuegoDTO;
import Modelo.IModelo;
import Vista.Objetos.FichaUI;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Point;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author benja
 */
public class VistaTablero extends javax.swing.JFrame implements Observador {

    private Controlador control;
    private boolean fichasInicializadas = false;

    /**
     * Creates new form VistaTableross
     */
    public VistaTablero(Controlador control) {
        this.control = control;
        this.setSize(920, 550);
        this.setTitle("Rummy Juego");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUIjuego = new javax.swing.JPanel();
        btnFinalizarTurno = new javax.swing.JLabel();
        panelFichasArmadas = new javax.swing.JPanel();
        panelJugador4 = new Vista.PanelRound();
        panelJugador1 = new Vista.PanelRound();
        panelMano = new Vista.PanelRound();
        fondoMano = new javax.swing.JLabel();
        panelJugador3 = new Vista.PanelRound();
        mazo = new Vista.PanelRound();
        btnMazo = new javax.swing.JLabel();
        panelJugador2 = new Vista.PanelRound();
        panelTablero = new javax.swing.JPanel();
        fondoPanelTablero = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GUIjuego.setBackground(new java.awt.Color(0, 0, 0));
        GUIjuego.setLayout(null);

        btnFinalizarTurno.setForeground(new java.awt.Color(255, 51, 51));
        btnFinalizarTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFinalizarTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalizarTurno.png"))); // NOI18N
        btnFinalizarTurno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFinalizarTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarTurnoMouseClicked(evt);
            }
        });
        GUIjuego.add(btnFinalizarTurno);
        btnFinalizarTurno.setBounds(790, 260, 100, 100);

        panelFichasArmadas.setBackground(new java.awt.Color(23, 57, 134));

        javax.swing.GroupLayout panelFichasArmadasLayout = new javax.swing.GroupLayout(panelFichasArmadas);
        panelFichasArmadas.setLayout(panelFichasArmadasLayout);
        panelFichasArmadasLayout.setHorizontalGroup(
            panelFichasArmadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelFichasArmadasLayout.setVerticalGroup(
            panelFichasArmadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        GUIjuego.add(panelFichasArmadas);
        panelFichasArmadas.setBounds(130, 0, 640, 120);

        panelJugador4.setRoundBottomLeft(40);
        panelJugador4.setRoundBottomRight(40);
        panelJugador4.setRoundTopLeft(40);
        panelJugador4.setRoundTopRight(40);

        javax.swing.GroupLayout panelJugador4Layout = new javax.swing.GroupLayout(panelJugador4);
        panelJugador4.setLayout(panelJugador4Layout);
        panelJugador4Layout.setHorizontalGroup(
            panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelJugador4Layout.setVerticalGroup(
            panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        GUIjuego.add(panelJugador4);
        panelJugador4.setBounds(0, 0, 120, 110);

        panelJugador1.setRoundBottomLeft(40);
        panelJugador1.setRoundBottomRight(40);
        panelJugador1.setRoundTopLeft(40);
        panelJugador1.setRoundTopRight(40);

        javax.swing.GroupLayout panelJugador1Layout = new javax.swing.GroupLayout(panelJugador1);
        panelJugador1.setLayout(panelJugador1Layout);
        panelJugador1Layout.setHorizontalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelJugador1Layout.setVerticalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        GUIjuego.add(panelJugador1);
        panelJugador1.setBounds(0, 390, 120, 110);

        panelMano.setRoundBottomLeft(40);
        panelMano.setRoundBottomRight(40);
        panelMano.setRoundTopLeft(40);
        panelMano.setRoundTopRight(40);
        panelMano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManoMouseClicked(evt);
            }
        });
        panelMano.setLayout(null);

        fondoMano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mano.png"))); // NOI18N
        fondoMano.setText("jLabel1");
        panelMano.add(fondoMano);
        fondoMano.setBounds(-50, -20, 650, 140);

        GUIjuego.add(panelMano);
        panelMano.setBounds(160, 380, 580, 120);

        panelJugador3.setRoundBottomLeft(40);
        panelJugador3.setRoundBottomRight(40);
        panelJugador3.setRoundTopLeft(40);
        panelJugador3.setRoundTopRight(40);

        javax.swing.GroupLayout panelJugador3Layout = new javax.swing.GroupLayout(panelJugador3);
        panelJugador3.setLayout(panelJugador3Layout);
        panelJugador3Layout.setHorizontalGroup(
            panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelJugador3Layout.setVerticalGroup(
            panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        GUIjuego.add(panelJugador3);
        panelJugador3.setBounds(780, 0, 120, 110);

        mazo.setBackground(new java.awt.Color(156, 113, 17));
        mazo.setRoundBottomLeft(40);
        mazo.setRoundBottomRight(40);
        mazo.setRoundTopLeft(40);
        mazo.setRoundTopRight(40);

        btnMazo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mazoGUI.png"))); // NOI18N
        btnMazo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMazo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMazoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mazoLayout = new javax.swing.GroupLayout(mazo);
        mazo.setLayout(mazoLayout);
        mazoLayout.setHorizontalGroup(
            mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMazo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        mazoLayout.setVerticalGroup(
            mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mazoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btnMazo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GUIjuego.add(mazo);
        mazo.setBounds(800, 150, 60, 87);

        panelJugador2.setRoundBottomLeft(40);
        panelJugador2.setRoundBottomRight(40);
        panelJugador2.setRoundTopLeft(40);
        panelJugador2.setRoundTopRight(40);

        javax.swing.GroupLayout panelJugador2Layout = new javax.swing.GroupLayout(panelJugador2);
        panelJugador2.setLayout(panelJugador2Layout);
        panelJugador2Layout.setHorizontalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelJugador2Layout.setVerticalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        GUIjuego.add(panelJugador2);
        panelJugador2.setBounds(780, 390, 120, 110);

        panelTablero.setBackground(new java.awt.Color(153, 153, 153));
        panelTablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelTableroMouseReleased(evt);
            }
        });
        panelTablero.setLayout(null);

        fondoPanelTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tablero.png"))); // NOI18N
        fondoPanelTablero.setText("jLabel1");
        panelTablero.add(fondoPanelTablero);
        fondoPanelTablero.setBounds(-50, 0, 750, 420);

        GUIjuego.add(panelTablero);
        panelTablero.setBounds(130, 130, 640, 242);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoRummy.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        GUIjuego.add(fondo);
        fondo.setBounds(0, 0, 900, 902);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(GUIjuego, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(GUIjuego, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelManoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelManoMouseClicked

    private void panelTableroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTableroMouseReleased

    }//GEN-LAST:event_panelTableroMouseReleased

    private void btnMazoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMazoMouseClicked
        control.pasarTurno();
    }//GEN-LAST:event_btnMazoMouseClicked

    private void btnFinalizarTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarTurnoMouseClicked
        control.terminarTurno();
    }//GEN-LAST:event_btnFinalizarTurnoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GUIjuego;
    private javax.swing.JLabel btnFinalizarTurno;
    private javax.swing.JLabel btnMazo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondoMano;
    private javax.swing.JLabel fondoPanelTablero;
    private Vista.PanelRound mazo;
    private javax.swing.JPanel panelFichasArmadas;
    private Vista.PanelRound panelJugador1;
    private Vista.PanelRound panelJugador2;
    private Vista.PanelRound panelJugador3;
    private Vista.PanelRound panelJugador4;
    private Vista.PanelRound panelMano;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualiza(IModelo modelo) {

        if (!fichasInicializadas) {
            inicializarFichasMano(modelo);
            fichasInicializadas = true; // marca que ya se ejecutó
        } else {
            pintarFichasTablero(modelo, control);
        }
    }

    public void pintarFichasTablero(IModelo modelo, Controlador controlador) {
        JuegoDTO juego = modelo.getTablero();
        List<GrupoDTO> grupos = juego.getGruposEnTablero();

        // Devolver fichas a la mano si no están en ningún grupo
        //devolverFichasAMano(modelo, grupos);
        // 2️⃣ Limpiar el panel del tablero antes de pintar
        panelFichasArmadas.removeAll();
        panelFichasArmadas.setBackground(new Color(23, 57, 134));
        panelFichasArmadas.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));

        // 3️⃣ Recorrer cada grupo
        for (GrupoDTO grupoDTO : grupos) {
            // Ignorar grupos no establecidos
            System.out.println(grupoDTO.getTipo());
            if (grupoDTO.getTipo().equals("No establecido")) {
                continue; // salta a la siguiente iteración
            }

            // Crear un panel para el grupo
            JPanel panelGrupo = new JPanel();
            panelGrupo.setBorder(BorderFactory.createTitledBorder(grupoDTO.getTipo()));
            panelGrupo.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));

            // Recorrer las fichas del grupo
            for (FichaJuegoDTO fichaDTO : grupoDTO.getFichasGrupo()) {
                // Crear un FichaUI en lugar de JButton
                FichaUI fichaUI = new FichaUI(
                        fichaDTO.getIdFicha(),
                        fichaDTO.getNumeroFicha(),
                        fichaDTO.getColor(),
                        fichaDTO.isComodin(),
                        controlador, this
                );

                fichaUI.setPreferredSize(new Dimension(20, 50));
                panelGrupo.add(fichaUI);

                // 🔹 Eliminar la ficha de la mano si existe allí
                modelo.getMano().removeIf(f -> f.getIdFicha() == fichaDTO.getIdFicha());
            }

            // Agregar el panel del grupo al tablero
            panelFichasArmadas.add(panelGrupo);
        }

        // 4️⃣ Refrescar la vista
        panelFichasArmadas.revalidate();
        panelFichasArmadas.repaint();
    }

    public void inicializarFichasMano(IModelo modelo) {
        List<FichaJuegoDTO> fichasMano = modelo.getMano();
        for (FichaJuegoDTO fichaJuegoDTO : fichasMano) {
            System.out.println("Ficha: " + fichaJuegoDTO);
        }
        // 1️⃣ Eliminar fichas antiguas de la mano
        for (Component c : GUIjuego.getComponents()) {
            if (c instanceof FichaUI && ((FichaUI) c).getOrigen() == FichaUI.Origen.MANO) {
                GUIjuego.remove(c);
            }
        }

        // 2️⃣ Posición inicial relativa al panelMano
        Point posPanel = panelMano.getLocation(); // posición dentro de GUIjuego
        int xPos = posPanel.x + 10;
        int yPos = posPanel.y + 10;

        // 3️⃣ Agregar fichas
        for (FichaJuegoDTO fichaDTO : fichasMano) {
            FichaUI fichaUI = new FichaUI(
                    fichaDTO.getIdFicha(),
                    fichaDTO.getNumeroFicha(),
                    fichaDTO.getColor(),
                    fichaDTO.isComodin(),
                    control, this
            );
            fichaUI.setOrigen(FichaUI.Origen.MANO);
            fichaUI.setSize(35, 50);
            fichaUI.setLocation(xPos, yPos);
            fichaUI.setOpaque(false);

            GUIjuego.add(fichaUI);
            GUIjuego.setComponentZOrder(fichaUI, 0);

            xPos += 40; // separación entre fichas
        }

        // 4️⃣ Actualizar GUI
        GUIjuego.revalidate();
        GUIjuego.repaint();
    }

    public JPanel getPanelTablero() {
        return panelTablero;
    }

}
