/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

/**
 *
 * @author chris
 */
public class EleccionColores extends javax.swing.JFrame {

    private RegistrarUsuario vistaPadre;
    private Color colorSeleccionado = null;

    // Colores default que no se repiten
    private final Color COLOR_SET_1 = new Color(185, 29, 29);   // Rojo Intenso
    private final Color COLOR_SET_2 = new Color(21, 101, 192);  // Azul Fuerte
    private final Color COLOR_SET_3 = new Color(46, 125, 50);   // Verde Bosque
    private final Color COLOR_SET_4 = new Color(249, 168, 37);  // Amarillo/Dorado Oscuro

    /**
     * Creates new form EleccionColores
     */
    public EleccionColores(RegistrarUsuario padre) {
        this.vistaPadre = padre;
        this.setTitle("RummyKub | Escoge tus set!");
        this.setSize(900, 500);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        initEstilos();
        initEventos();
    }

    public EleccionColores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSet4 = new javax.swing.JLabel();
        btnSet3 = new javax.swing.JLabel();
        btnSet2 = new javax.swing.JLabel();
        btnSet1 = new javax.swing.JLabel();
        Color4 = new vista.PanelRound();
        Color3 = new vista.PanelRound();
        Color2 = new vista.PanelRound();
        Color1 = new vista.PanelRound();
        fondoBtnRegresar = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JLabel();
        fondoBtnConfirmar = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JLabel();
        txtSet4 = new javax.swing.JLabel();
        txtSet3 = new javax.swing.JLabel();
        txtSet2 = new javax.swing.JLabel();
        txtSet1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSet4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paint.png"))); // NOI18N
        getContentPane().add(btnSet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 50, 50));

        btnSet3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paint.png"))); // NOI18N
        getContentPane().add(btnSet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 50, 50));

        btnSet2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paint.png"))); // NOI18N
        getContentPane().add(btnSet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 50, 50));

        btnSet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paint.png"))); // NOI18N
        getContentPane().add(btnSet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 50, 50));

        Color4.setRoundBottomLeft(80);
        Color4.setRoundBottomRight(80);
        Color4.setRoundTopLeft(80);
        Color4.setRoundTopRight(80);

        javax.swing.GroupLayout Color4Layout = new javax.swing.GroupLayout(Color4);
        Color4.setLayout(Color4Layout);
        Color4Layout.setHorizontalGroup(
            Color4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        Color4Layout.setVerticalGroup(
            Color4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Color4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        Color3.setRoundBottomLeft(80);
        Color3.setRoundBottomRight(80);
        Color3.setRoundTopLeft(80);
        Color3.setRoundTopRight(80);

        javax.swing.GroupLayout Color3Layout = new javax.swing.GroupLayout(Color3);
        Color3.setLayout(Color3Layout);
        Color3Layout.setHorizontalGroup(
            Color3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        Color3Layout.setVerticalGroup(
            Color3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Color3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        Color2.setRoundBottomLeft(80);
        Color2.setRoundBottomRight(80);
        Color2.setRoundTopLeft(80);
        Color2.setRoundTopRight(80);

        javax.swing.GroupLayout Color2Layout = new javax.swing.GroupLayout(Color2);
        Color2.setLayout(Color2Layout);
        Color2Layout.setHorizontalGroup(
            Color2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        Color2Layout.setVerticalGroup(
            Color2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Color2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        Color1.setRoundBottomLeft(80);
        Color1.setRoundBottomRight(80);
        Color1.setRoundTopLeft(80);
        Color1.setRoundTopRight(80);

        javax.swing.GroupLayout Color1Layout = new javax.swing.GroupLayout(Color1);
        Color1.setLayout(Color1Layout);
        Color1Layout.setHorizontalGroup(
            Color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        Color1Layout.setVerticalGroup(
            Color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 40, 40));

        fondoBtnRegresar.setBackground(new java.awt.Color(206, 70, 70));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout fondoBtnRegresarLayout = new javax.swing.GroupLayout(fondoBtnRegresar);
        fondoBtnRegresar.setLayout(fondoBtnRegresarLayout);
        fondoBtnRegresarLayout.setHorizontalGroup(
            fondoBtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        fondoBtnRegresarLayout.setVerticalGroup(
            fondoBtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(fondoBtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 170, 50));

        fondoBtnConfirmar.setBackground(new java.awt.Color(255, 235, 126));

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(204, 102, 0));
        btnConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirmar.setText("Confirmar");

        javax.swing.GroupLayout fondoBtnConfirmarLayout = new javax.swing.GroupLayout(fondoBtnConfirmar);
        fondoBtnConfirmar.setLayout(fondoBtnConfirmarLayout);
        fondoBtnConfirmarLayout.setHorizontalGroup(
            fondoBtnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        fondoBtnConfirmarLayout.setVerticalGroup(
            fondoBtnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(fondoBtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 180, 60));

        txtSet4.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        txtSet4.setForeground(new java.awt.Color(255, 255, 255));
        txtSet4.setText("SET 4");
        getContentPane().add(txtSet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        txtSet3.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        txtSet3.setForeground(new java.awt.Color(255, 255, 255));
        txtSet3.setText("SET 3");
        getContentPane().add(txtSet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        txtSet2.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        txtSet2.setForeground(new java.awt.Color(255, 255, 255));
        txtSet2.setText("SET 2");
        getContentPane().add(txtSet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        txtSet1.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        txtSet1.setForeground(new java.awt.Color(255, 255, 255));
        txtSet1.setText("SET 1");
        getContentPane().add(txtSet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(246, 220, 105));
        txtTitulo.setText("Elige los colores de tus fichas");
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRummy.png"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initEstilos() {
        Color1.setBackground(COLOR_SET_1);
        Color2.setBackground(COLOR_SET_2);
        Color3.setBackground(COLOR_SET_3);
        Color4.setBackground(COLOR_SET_4);
    }

    private void initEventos() {
        // Eventos para abrir el selector (usando los paneles correctos)
        btnSet1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mostrarMiniSelectorColor(Color1); // <--- Usar Color1
            }
        });

        btnSet2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mostrarMiniSelectorColor(Color2); // <--- Usar Color2
            }
        });

        btnSet3.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mostrarMiniSelectorColor(Color3); // <--- Usar Color3
            }
        });

        btnSet4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mostrarMiniSelectorColor(Color4); // <--- Usar Color4
            }
        });

        // LOGICA DE CONFIRMAR (Estaba comentada y con variables incorrectas)
        btnConfirmar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // 1. Obtenemos los colores de los paneles (Color1, Color2...)
                Color c1 = Color1.getBackground();
                Color c2 = Color2.getBackground();
                Color c3 = Color3.getBackground();
                Color c4 = Color4.getBackground();

                // 2. Verificamos duplicados
                if (c1.equals(c2) || c1.equals(c3) || c1.equals(c4)
                        || c2.equals(c3) || c2.equals(c4)
                        || c3.equals(c4)) {

                    JOptionPane.showMessageDialog(EleccionColores.this,
                            "Has seleccionado colores repetidos.\nPor favor, elige un color distinto para cada Set.",
                            "Colores Duplicados",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // 3. Enviamos los colores a la ventana padre y cerramos
                vistaPadre.actualizarColoresUsuario(c1, c2, c3, c4);
                dispose();
                vistaPadre.setVisible(true);
            }
        });

        // Botón Regresar
        btnRegresar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                vistaPadre.setVisible(true);
            }
        });
    }

    /**
     * Mini menu con colores limitados para elegir
     *
     * Popup que aparecerá al lado del botón
     *
     * @param panelDestino
     */
   private void mostrarMiniSelectorColor(JPanel panelDestino) {
        JPopupMenu popup = new JPopupMenu();
        // Grid de 2 filas x 6 columnas
        JPanel grid = new JPanel(new java.awt.GridLayout(2, 6, 5, 5));
        grid.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        // --- 2. LISTA DE COLORES DEL SELECTOR (PALETA OSCURA) ---
        Color[] colores = {
            new Color(185, 29, 29),   // Rojo Intenso
            new Color(21, 101, 192),  // Azul Fuerte
            new Color(46, 125, 50),   // Verde Bosque
            new Color(249, 168, 37),  // Dorado
            new Color(230, 81, 0),    // Naranja Oscuro
            new Color(74, 20, 140),   // Morado/Violeta Oscuro
            new Color(0, 96, 100),    // Cyan Oscuro (Teal)
            new Color(136, 14, 79),   // Rosa Mexicano/Fucsia Oscuro
            new Color(62, 39, 35),    // Café/Marrón
            new Color(66, 66, 66),    // Gris Oscuro
            new Color(13, 71, 161),   // Azul Marino Profundo
            new Color(0, 0, 0)        // Negro
        };

        for (Color c : colores) {
            JPanel cuadrito = new JPanel();
            cuadrito.setBackground(c);
            cuadrito.setPreferredSize(new java.awt.Dimension(30, 30)); // Un poco más grandes
            cuadrito.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
            
            // Cursor de mano para que se vea clicable
            cuadrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

            cuadrito.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    panelDestino.setBackground(c); // Actualiza el panel seleccionado
                    popup.setVisible(false);       // Cierra el popup
                }
            });

            grid.add(cuadrito);
        }

        popup.add(grid);
        // Mostrar popup debajo del panel destino
        popup.show(panelDestino, 0, panelDestino.getHeight());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelRound Color1;
    private vista.PanelRound Color2;
    private vista.PanelRound Color3;
    private vista.PanelRound Color4;
    private javax.swing.JLabel btnConfirmar;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JLabel btnSet1;
    private javax.swing.JLabel btnSet2;
    private javax.swing.JLabel btnSet3;
    private javax.swing.JLabel btnSet4;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondoBtnConfirmar;
    private javax.swing.JPanel fondoBtnRegresar;
    private javax.swing.JLabel txtSet1;
    private javax.swing.JLabel txtSet2;
    private javax.swing.JLabel txtSet3;
    private javax.swing.JLabel txtSet4;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
