/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

/**
 *
 * @author chris
 */
public class EleccionColores extends javax.swing.JFrame {

    private RegistrarUsuario vistaPadre;
    private Color colorSeleccionado = null;

    //colores default que no se repiten
    private final Color COLOR_SET_1 = new Color(255, 102, 102); // Rojo suave
    private final Color COLOR_SET_2 = new Color(102, 204, 255); // Azul cielo
    private final Color COLOR_SET_3 = new Color(153, 255, 153); // Verde claro
    private final Color COLOR_SET_4 = new Color(255, 255, 153); // Amarillo claro

    /**
     * Creates new form EleccionColores
     */
    public EleccionColores(RegistrarUsuario padre) {
        this.vistaPadre = padre;
        this.setTitle("RummyKub | Escoge tus set!");
        this.setSize(920, 550);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        initEstilos();
        initEventos();
    }

    public EleccionColores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSet4 = new javax.swing.JLabel();
        btnSet3 = new javax.swing.JLabel();
        btnSet2 = new javax.swing.JLabel();
        btnSet1 = new javax.swing.JLabel();
        colorSet4 = new javax.swing.JPanel();
        colorSet3 = new javax.swing.JPanel();
        colorSet2 = new javax.swing.JPanel();
        colorSet1 = new javax.swing.JPanel();
        fondoBtnRegresar = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JLabel();
        fondoBtnConfirmar = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JLabel();
        txtSet4 = new javax.swing.JLabel();
        txtSet3 = new javax.swing.JLabel();
        txtSet2 = new javax.swing.JLabel();
        txtSet1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSet4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubeta.png"))); // NOI18N
        getContentPane().add(btnSet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 50, 50));

        btnSet3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubeta.png"))); // NOI18N
        getContentPane().add(btnSet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 50, 50));

        btnSet2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubeta.png"))); // NOI18N
        getContentPane().add(btnSet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 50, 50));

        btnSet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubeta.png"))); // NOI18N
        getContentPane().add(btnSet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 50, 50));

        colorSet4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout colorSet4Layout = new javax.swing.GroupLayout(colorSet4);
        colorSet4.setLayout(colorSet4Layout);
        colorSet4Layout.setHorizontalGroup(
            colorSet4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        colorSet4Layout.setVerticalGroup(
            colorSet4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(colorSet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        colorSet3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout colorSet3Layout = new javax.swing.GroupLayout(colorSet3);
        colorSet3.setLayout(colorSet3Layout);
        colorSet3Layout.setHorizontalGroup(
            colorSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        colorSet3Layout.setVerticalGroup(
            colorSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(colorSet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 50, 50));

        colorSet2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout colorSet2Layout = new javax.swing.GroupLayout(colorSet2);
        colorSet2.setLayout(colorSet2Layout);
        colorSet2Layout.setHorizontalGroup(
            colorSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        colorSet2Layout.setVerticalGroup(
            colorSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(colorSet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 50, 50));

        colorSet1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout colorSet1Layout = new javax.swing.GroupLayout(colorSet1);
        colorSet1.setLayout(colorSet1Layout);
        colorSet1Layout.setHorizontalGroup(
            colorSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        colorSet1Layout.setVerticalGroup(
            colorSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(colorSet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 50, 50));

        fondoBtnRegresar.setBackground(new java.awt.Color(206, 70, 70));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout fondoBtnRegresarLayout = new javax.swing.GroupLayout(fondoBtnRegresar);
        fondoBtnRegresar.setLayout(fondoBtnRegresarLayout);
        fondoBtnRegresarLayout.setHorizontalGroup(
            fondoBtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        fondoBtnRegresarLayout.setVerticalGroup(
            fondoBtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(fondoBtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 170, 50));

        fondoBtnConfirmar.setBackground(new java.awt.Color(255, 235, 126));

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(204, 102, 0));
        btnConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirmar.setText("Confirmar");

        javax.swing.GroupLayout fondoBtnConfirmarLayout = new javax.swing.GroupLayout(fondoBtnConfirmar);
        fondoBtnConfirmar.setLayout(fondoBtnConfirmarLayout);
        fondoBtnConfirmarLayout.setHorizontalGroup(
            fondoBtnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        fondoBtnConfirmarLayout.setVerticalGroup(
            fondoBtnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(fondoBtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 180, 60));

        txtSet4.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        txtSet4.setForeground(new java.awt.Color(255, 255, 255));
        txtSet4.setText("SET 4");
        getContentPane().add(txtSet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        txtSet3.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        txtSet3.setForeground(new java.awt.Color(255, 255, 255));
        txtSet3.setText("SET 3");
        getContentPane().add(txtSet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        txtSet2.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        txtSet2.setForeground(new java.awt.Color(255, 255, 255));
        txtSet2.setText("SET 2");
        getContentPane().add(txtSet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        txtSet1.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        txtSet1.setForeground(new java.awt.Color(255, 255, 255));
        txtSet1.setText("SET 1");
        getContentPane().add(txtSet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(246, 220, 105));
        txtTitulo.setText("Elegir Colores");
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRummy.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initEstilos() {
        // Asignar los colores a los paneles visuales
        colorSet1.setBackground(COLOR_SET_1);
        colorSet2.setBackground(COLOR_SET_2);
        colorSet3.setBackground(COLOR_SET_3);
        colorSet4.setBackground(COLOR_SET_4);
    }

    private void initEventos() {
        btnSet1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mostrarMiniSelectorColor(colorSet1);
            }
        });

        btnSet2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mostrarMiniSelectorColor(colorSet2);
            }
        });

        btnSet3.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mostrarMiniSelectorColor(colorSet3);
            }
        });

        btnSet4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mostrarMiniSelectorColor(colorSet4);
            }
        });

        btnConfirmar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // obtenemos los colores actuales de los paneles
                Color c1 = colorSet1.getBackground();
                Color c2 = colorSet2.getBackground();
                Color c3 = colorSet3.getBackground();
                Color c4 = colorSet4.getBackground();

                // despues verificamos todas las combinaciones posibles de duplicados (cada set debe tener si o si un color distinto)
                if (c1.equals(c2) || c1.equals(c3) || c1.equals(c4)
                        || c2.equals(c3) || c2.equals(c4)
                        || c3.equals(c4)) {

                    // Si se encuentran repetidos, mostramos el mensaje y NO cerramos la ventana (osea, no se puede continuar)
                    JOptionPane.showMessageDialog(EleccionColores.this,
                            "Has seleccionado colores repetidos.\nPor favor, elige un color distinto para cada Set.",
                            "Colores Duplicados",
                            JOptionPane.WARNING_MESSAGE);
                    return; // El return detiene la ejecución aquí
                }

                // Cuando todo ya está correcto, permite guardar y salimos
                vistaPadre.actualizarColoresUsuario(c1, c2, c3, c4);
                dispose();
                vistaPadre.setVisible(true);
            }
        });

        // Listener Botón Regresar
        btnRegresar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                vistaPadre.setVisible(true);
            }
        });
    }

    private void mostrarMiniSelectorColor(JPanel panelDestino) {
        // Popup que aparecerá al lado del botón
        JPopupMenu popup = new JPopupMenu();
        JPanel grid = new JPanel(new java.awt.GridLayout(2, 6, 5, 5));
        grid.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        // Colores disponibles
        Color[] colores = {
            Color.RED, Color.BLUE, Color.GREEN, Color.YELLOW,
            Color.ORANGE, Color.MAGENTA, Color.CYAN, Color.PINK,
            Color.GRAY, Color.BLACK, Color.WHITE, new Color(128, 0, 255)
        };

        for (Color c : colores) {
            JPanel cuadrito = new JPanel();
            cuadrito.setBackground(c);
            cuadrito.setPreferredSize(new java.awt.Dimension(25, 25));
            cuadrito.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));

            cuadrito.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    panelDestino.setBackground(c); // Actualiza visualmente el panel
                    popup.setVisible(false);

                }
            });

            grid.add(cuadrito);
        }

        popup.add(grid);

        // Mostrar popup debajo del panel destino
        popup.show(panelDestino, panelDestino.getWidth(), 0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConfirmar;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JLabel btnSet1;
    private javax.swing.JLabel btnSet2;
    private javax.swing.JLabel btnSet3;
    private javax.swing.JLabel btnSet4;
    private javax.swing.JPanel colorSet1;
    private javax.swing.JPanel colorSet2;
    private javax.swing.JPanel colorSet3;
    private javax.swing.JPanel colorSet4;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondoBtnConfirmar;
    private javax.swing.JPanel fondoBtnRegresar;
    private javax.swing.JLabel txtSet1;
    private javax.swing.JLabel txtSet2;
    private javax.swing.JLabel txtSet3;
    private javax.swing.JLabel txtSet4;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
