/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import TipoEventos.EventoRegistro;
import contratos.controladoresMVC.iControlCUPrincipal;
import contratos.controladoresMVC.iControlRegistro;
import contratos.iNavegacion;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author chris
 */
public class RegistrarUsuario extends javax.swing.JFrame implements ObservadorRegistro {

    private iControlRegistro control;
    private iNavegacion navegacion;

    //Valores por defecto del usuario
    private String avatarSeleccionado = "avatar1";
    private Color colorSeleccionado = Color.WHITE;
    private Border bordeSeleccion = BorderFactory.createLineBorder(Color.RED, 3);

    // Colores de los 4 sets
    private Color colorSet1;
    private Color colorSet2;
    private Color colorSet3;
    private Color colorSet4;

    /**
     * Creates new form RegistrarUsuario
     *
     * @param control
     */
    public RegistrarUsuario(iControlRegistro control) {
        this.control = control;
        this.setTitle("RummyKub | Vive la experiencia!");
        this.setSize(920, 550);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        initComponents();
        initEvents();
        initAvatarSelection();

        // Avatares al frente
        jPanel1.setComponentZOrder(avatar1, 0);
        jPanel1.setComponentZOrder(avatar2, 0);
        jPanel1.setComponentZOrder(avatar3, 0);
        jPanel1.setComponentZOrder(avatar4, 0);
    }

    /**
     * Evento para el botón "Registrar"
     */
    private void initEvents() {
        btnRegistrar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String nombre = txtfldNombre.getText();
                if (!nombre.trim().isEmpty()) {

                    if (colorSet1 == null) { //color inicial de las fichas?
                        colorSet1 = Color.RED;
                        colorSet2 = Color.GREEN;
                        colorSet3 = Color.YELLOW;
                        colorSet4 = Color.BLUE;
                    }

                    control.intentarRegistrar(
                            nombre,
                            avatarSeleccionado,
                            colorSet1, colorSet2, colorSet3, colorSet4
                    );

                } else {
                    JOptionPane.showMessageDialog(null, "Por favor ingresa un nombre.");
                }
            }
        });

    }

    /**
     * Lógica para resaltar el avatar seleccionado
     *
     */
    private void initAvatarSelection() {
        MouseAdapter selector = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                avatar1.setBorder(null);
                avatar2.setBorder(null);
                avatar3.setBorder(null);
                avatar4.setBorder(null);

                //se le asigna un borde al seleccionado y guardamos el nombre
                JLabel fuente = (JLabel) e.getSource();
                fuente.setBorder(bordeSeleccion);

                if (fuente == avatar1) {
                    avatarSeleccionado = "1";
                } else if (fuente == avatar2) {
                    avatarSeleccionado = "2";
                } else if (fuente == avatar3) {
                    avatarSeleccionado = "3";
                } else if (fuente == avatar4) {
                    avatarSeleccionado = "4";
                }
            }
        };

        avatar1.addMouseListener(selector);
        avatar2.addMouseListener(selector);
        avatar3.addMouseListener(selector);
        avatar4.addMouseListener(selector);

        // El primer icono se escoge por defecto
        avatar1.setBorder(bordeSeleccion);

        // Listener para el Color
        btnColor.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                abrirEleccionColores();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        btnColor = new javax.swing.JLabel();
        txtfldNombre = new javax.swing.JTextField();
        txt2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txtSubtitulo = new javax.swing.JLabel();
        avatar4 = new javax.swing.JLabel();
        avatar3 = new javax.swing.JLabel();
        avatar2 = new javax.swing.JLabel();
        avatar1 = new javax.swing.JLabel();
        fondoavatar4 = new javax.swing.JPanel();
        fondoAvatar3 = new javax.swing.JPanel();
        fondoAvatar2 = new javax.swing.JPanel();
        fondoAvatar1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(246, 220, 105));
        panel.setForeground(new java.awt.Color(246, 220, 105));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(153, 102, 0));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("Registrarse");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 210, 60));

        btnColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/color.png"))); // NOI18N
        jPanel1.add(btnColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        txtfldNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtfldNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtfldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 410, 40));

        txt2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setText("Color de fichas:");
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        txt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setText("Nombre:");
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        txtSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtitulo.setText("Seleccionar Avatar:");
        jPanel1.add(txtSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        avatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatares/avatar4.png"))); // NOI18N
        jPanel1.add(avatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 70, 70));

        avatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatares/avatar3.png"))); // NOI18N
        jPanel1.add(avatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 70, 70));

        avatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatares/avatar2.png"))); // NOI18N
        jPanel1.add(avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 70, 70));

        avatar1.setBackground(new java.awt.Color(255, 255, 255));
        avatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatares/avatar1.png"))); // NOI18N
        jPanel1.add(avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 70, 70));

        fondoavatar4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fondoavatar4Layout = new javax.swing.GroupLayout(fondoavatar4);
        fondoavatar4.setLayout(fondoavatar4Layout);
        fondoavatar4Layout.setHorizontalGroup(
            fondoavatar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        fondoavatar4Layout.setVerticalGroup(
            fondoavatar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(fondoavatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 70, 70));

        fondoAvatar3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fondoAvatar3Layout = new javax.swing.GroupLayout(fondoAvatar3);
        fondoAvatar3.setLayout(fondoAvatar3Layout);
        fondoAvatar3Layout.setHorizontalGroup(
            fondoAvatar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        fondoAvatar3Layout.setVerticalGroup(
            fondoAvatar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(fondoAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 70, 70));

        fondoAvatar2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fondoAvatar2Layout = new javax.swing.GroupLayout(fondoAvatar2);
        fondoAvatar2.setLayout(fondoAvatar2Layout);
        fondoAvatar2Layout.setHorizontalGroup(
            fondoAvatar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        fondoAvatar2Layout.setVerticalGroup(
            fondoAvatar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(fondoAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 70, 70));

        fondoAvatar1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fondoAvatar1Layout = new javax.swing.GroupLayout(fondoAvatar1);
        fondoAvatar1.setLayout(fondoAvatar1Layout);
        fondoAvatar1Layout.setHorizontalGroup(
            fondoAvatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        fondoAvatar1Layout.setVerticalGroup(
            fondoAvatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(fondoAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 70, 70));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(246, 220, 105));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Registrar Usuario");
        txtTitulo.setToolTipText("");
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 450, 70));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRummy.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldNombreActionPerformed

    private void abrirEleccionColores() {
        EleccionColores ventanaColores = new EleccionColores(this);
        ventanaColores.setVisible(true);
    }

    public void setNavegacion(iNavegacion navegacion) {
        this.navegacion = navegacion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar1;
    private javax.swing.JLabel avatar2;
    private javax.swing.JLabel avatar3;
    private javax.swing.JLabel avatar4;
    private javax.swing.JLabel btnColor;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondoAvatar1;
    private javax.swing.JPanel fondoAvatar2;
    private javax.swing.JPanel fondoAvatar3;
    private javax.swing.JPanel fondoavatar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txtSubtitulo;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField txtfldNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualiza(EventoRegistro evento, String mensaje) {
        switch (evento) {
            case REGISTRO_EXITOSO:
                System.out.println("[VistaRegistro] Registro exitoso. Cerrando y navegando...");
                // 1. Cerrar la vista actual
                this.setVisible(false);

                control.entrarSalaEspera();

                break;

            case NOMBRE_REPETIDO:
                mostrarError("El nombre ya está en uso.");
                break;

            case ABRIR_VENTANA:
                this.setVisible(true);
                this.toFront();
                break;
        }
    }

    /**
     * Método público llamado por EleccionColores
     *
     * @param c1
     * @param c2
     * @param c3
     * @param c4
     */
    public void actualizarColoresUsuario(Color c1, Color c2, Color c3, Color c4) {
        this.colorSet1 = c1;
        this.colorSet2 = c2;
        this.colorSet3 = c3;
        this.colorSet4 = c4;

        this.colorSeleccionado = c1;

        btnColor.setOpaque(true);
        btnColor.setBackground(c1); // podrías hacer algo más fancy luego
        btnColor.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
    }

    /**
     * Muestra un mensaje de error al usuario. Llamado por el controlador cuando
     * el servidor devuelve un error (ej. Nombre repetido).
     */
    public void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this,
                mensaje,
                "Error de Registro",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

}
