/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Controlador;
import eventos.Evento;
import modelo.IModelo;


/**
 *
 * @author benja
 */
public class ConfigurarPartida extends javax.swing.JFrame implements Observador {

    /**
     * Creates new form VistaLobby
     */
    Controlador control;

    public ConfigurarPartida(Controlador control) {
        this.control = control;
        this.setTitle("RummyKub | Vive la experiencia!");
        this.setSize(920, 550);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNumComodines = new javax.swing.JLabel();
        spinnerComidines = new javax.swing.JSpinner();
        btn13Fichas1 = new vista.PanelRound();
        btn13Fichas2 = new vista.PanelRound();
        btn13Fichas3 = new vista.PanelRound();
        fondoRummy = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 220, 105));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Configurar Partida");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 20, 900, 90);

        txtNumComodines.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNumComodines.setForeground(new java.awt.Color(255, 255, 255));
        txtNumComodines.setText("Numero de Comodines");
        getContentPane().add(txtNumComodines);
        txtNumComodines.setBounds(190, 140, 280, 32);
        getContentPane().add(spinnerComidines);
        spinnerComidines.setBounds(450, 150, 260, 22);

        btn13Fichas1.setBackground(new java.awt.Color(246, 220, 105));
        btn13Fichas1.setRoundBottomLeft(30);
        btn13Fichas1.setRoundBottomRight(30);
        btn13Fichas1.setRoundTopLeft(30);
        btn13Fichas1.setRoundTopRight(30);

        javax.swing.GroupLayout btn13Fichas1Layout = new javax.swing.GroupLayout(btn13Fichas1);
        btn13Fichas1.setLayout(btn13Fichas1Layout);
        btn13Fichas1Layout.setHorizontalGroup(
            btn13Fichas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btn13Fichas1Layout.setVerticalGroup(
            btn13Fichas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(btn13Fichas1);
        btn13Fichas1.setBounds(470, 210, 240, 60);

        btn13Fichas2.setBackground(new java.awt.Color(246, 220, 105));
        btn13Fichas2.setRoundBottomLeft(30);
        btn13Fichas2.setRoundBottomRight(30);
        btn13Fichas2.setRoundTopLeft(30);
        btn13Fichas2.setRoundTopRight(30);
        getContentPane().add(btn13Fichas2);
        btn13Fichas2.setBounds(320, 300, 240, 70);

        btn13Fichas3.setBackground(new java.awt.Color(246, 220, 105));
        btn13Fichas3.setRoundBottomLeft(30);
        btn13Fichas3.setRoundBottomRight(30);
        btn13Fichas3.setRoundTopLeft(30);
        btn13Fichas3.setRoundTopRight(30);
        getContentPane().add(btn13Fichas3);
        btn13Fichas3.setBounds(170, 210, 240, 60);

        fondoRummy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRummy.jpg"))); // NOI18N
        fondoRummy.setText("NN");
        fondoRummy.setMaximumSize(new java.awt.Dimension(900, 500));
        fondoRummy.setMinimumSize(new java.awt.Dimension(900, 500));
        fondoRummy.setName(""); // NOI18N
        fondoRummy.setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().add(fondoRummy);
        fondoRummy.setBounds(-4, -4, 910, 510);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelRound btn13Fichas1;
    private vista.PanelRound btn13Fichas2;
    private vista.PanelRound btn13Fichas3;
    private javax.swing.JLabel fondoRummy;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spinnerComidines;
    private javax.swing.JLabel txtNumComodines;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualiza(IModelo modelo, Evento evento) {
        switch (evento) {
            case CREAR_PARTIDA:
                
                System.out.println("Viajando MVC CrearPartida");
                this.setVisible(false);
                break;

            case SOLICITAR_INICIO:

                break;
            default:
                throw new AssertionError();
        }
    }
}
